name: ci

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean install
      - run: ls -ltr bootstrap/target/bootstrap-0.0.1-SNAPSHOT.jar
      #- run: docker build .  --file Dockerfile
      #- run: docker build -t bitcoin-backend-image --file Dockerfile
      #- run: docker build -f Dockerfile -t bitcoin-backend-image .
      #- run: docker run bitcoin-backend-image

